### PR TITLE
Add a Turing machine

### PR DESCRIPTION
**Pull request by omentic**
- [x] I added myself to [`people.json`](./people.json)!

This is a Turing machine that prints the Fibonacci sequence in binary, forever.

It opens the door to a couple of other ideas I had...

### CODE REVIEW

**Comment by braxtonhall** [comment]
oh my god

**Review by braxtonhall — COMMENTED** [review]
um ok not that i want to be talking about dumb details when there is all this greek to look at, but should your title be BSc _Student_.

this will definitely be part of the submission to the exhibition, so I want to make sure it's accurate lol

**Comment by jyoo980** [comment]
@j-james pls respond to my email re: The William J. Bowman Rickroll Charity Competition

**Comment by omentic** [comment]
@jyoo980 omg

i thought i did months ago aaaa

**Pull request merged**
