### PR TITLE
Katharine's contribution with a basic fib

### PR DESCRIPTION
**Pull request by kekerr**
:D

### CODE REVIEW

**Comment by braxtonhall** [comment]
👀

**Comment by kekerr** [comment]
haha fixing this up

**Comment by kekerr** [comment]
fewf, almost thought I forgot how to use git!

**Comment by kekerr** [comment]
@braxtonhall it's now ready for review

**Comment by kekerr** [comment]
Ahhhhh no it isn't

**Comment by kekerr** [comment]
YESSHH it is now ready

**Comment by braxtonhall** [comment]
let's just see what happens if i merge anyway

**Pull request merged**
